### ISSUE TITLE
difference between two arXiv versions

### ISSUE THREAD

**Issue by RuyiLian** [suyz526/ZebraPose#2]
Hi,

I find out that you have uploaded a new version of your paper in arXiv, and the performances are greatly improved compared with v1. However, I could not figure out what contributed to such significant improvement. Could you help clarify this? Thanks very much!

**Comment by suyz526** [comment]
Hi,

Thanks for the question. We planned to explain this together with the open-source code. But I can make it a bit clear now. 

We fixed a bug, which is not related to the method, and we even do not need to train the CNN again. The bug is only related to the inference stage.

The PnP solver requires the 2D pixel location in the original image, not its location in the ROI. Given the 4 corners of the ROI, we can map a 2D location within the ROI back to the location of the original image. 

The problem was:
We always expand the ROI to 1.5 times its original size. If the corners of the expanded ROI is out of the image, we clip it to zero or saturate it. Let the ROI be expressed as (min_x, miny, max_x, max_y). For the bounding box (0, 0, 20, 20), it will be expanded to (-5, -5, 25, 25), and then be clipped as (0, 0, 25, 25). Previously we forgot to consider this clipped operation during the inference. So for a pixel belonging to a big object or object near the image boundary, its 2D location in the original image will be calculated wrong.

This will not influence the training but only the inference. We added 1 in the dataloader function to fix this. We get the results in v2 using the same checkpoints as in v1. Later we will point out this in the readme. And if you comment out that line, you will get the results provided in v1.

For any further questions, please don't hesitate to contact me.

**Comment by suyz526** [comment]
> Thanks for your detailed explanation! I see GDR-Net directly saves original location for each pixel: https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/114cff27c6fc6048724a6f2bdce2306ab51d798e/core/gdrn_modeling/data_loader.py#L436. Will this also fix the issue?

Unlike SO-Pose, we didn't use much code from GDR-Net. So the described bug only exists in our previous code. 

But of course, getting the original location can be implemented in different ways. You can have a function to compute the original location, or save the original location as GDR-Net did.

**Comment by suyz526** [comment]
> > Thanks for your detailed explanation! I see GDR-Net directly saves original location for each pixel: https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/114cff27c6fc6048724a6f2bdce2306ab51d798e/core/gdrn_modeling/data_loader.py#L436. Will this also fix the issue?
> 
> Unlike SO-Pose, we didn't use much code from GDR-Net. So the described bug only exists in our previous code.
> 
> But of course, getting the original location can be implemented in different ways. You can have a function to compute the original location, or save the original location as GDR-Net did.

I guess GDR-Net needs to save it because they train the network end-to-end.

**Comment by RuyiLian** [comment]
Got it, thanks! Looking forward to your released codes :)
