### ISSUE TITLE
module 'cv2' has no attribute 'ppf_match_3d_ICP'

### ISSUE THREAD

**Issue by smoothumut** [suyz526/ZebraPose#25]
Hi suyz526, 

Thanks, thanks a lot work your great work. I have big hopes with our dataset for your project if I can make it work of course. I have been working for 3 days to make it work. Especially render module became a torture for me : ) 

Anyway, I am very close to see the refined positions on renderer but I am getting error like below

AttributeError: module 'cv2' has no attribute 'ppf_match_3d_ICP'

on code line 129 on icp_refiner_modified.py.

icp_fnc = cv.ppf_match_3d_ICP(n_iters, tolerence=tolerence, numLevels=4)

I am misssing something but I couldnt figure out.

I have installed the below modules:
pip install opencv-python==4.5.4.58
pip install opencv-contrib-python==4.5.4.60

but I am still having the same problem. cv2 cannot find surface matching module and ppf. 

Do you have any suggestion for this problem?
thanks thanks in advance

**Comment by suyz526** [comment]
Hi, 

Thanks a lot for your interest. I just have run a quick test, but I'm unable to reproduce the error.

I created a virtual environment with
`virtualenv -p python3 test_opencv_contrib` and then `source test_opencv_contrib/bin/activate`

And installed the package with
`pip install opencv-python==4.5.4.58` and `pip install opencv-contrib-python==4.5.4.60`

Then I tried
`from cv2 import ppf_match_3d_ICP`

I didn't see any errors in my machine. Would you please check if opencv-contrib-python is successfully installed?


Best Regards,
Yongzhi

**Comment by smoothumut** [comment]
Hi Yongzhi,

Thank you very much for your reply and support. It was my bad : ) I delete the environment and create brand new one with installing the minimum required packages in need. Now as you described above, it worked. while I was struggling with c++ and the packages, I guess  I had messed up little. Now I have made the "test_vivo.py" work. it runs. it calculates the neighborhoods, it logs their calculation time, and sometimes it says "not enough points for ICP". but the opengl render window is total black. this is what it is supposed to be?

Best Regards
Umut

**Comment by smoothumut** [comment]
Here are my updates Yongzhi

I have changed the line 185 and 187 on opengl_render.cpp  . then compile it. it now works. (By the way I need to copy and paste libglad.so and ligopengl_render.so from build to /usr/lib , otherwise I couldnt make it work)   

I run the test_vivo.py. it makes calculations and show red mask, that is great. But...

Somehow, in some runs of test_vivo.py , it doesnt show the red mask on renderer even though it logs calculation times. ( it does sometimes say  not enough icp points. not always )

I run it with vs code debugging. I have tested the render using ICP_Render.py  and it has the same problem. sometimes show the red mask sometimes not

is this normal, or I have messed up somethings..

thanks thanks in advance 
Umut

**Comment by suyz526** [comment]
Hi Umut,

The calculation time might be from the ProgressiveX, not from the renderer? You can disable ProgressiveX by setting [here](https://github.com/suyz526/ZebraPose/blob/06b53d2aab1f5e08ffc927b6c5a02e9913cb13f8/zebrapose/binary_code_helper/CNN_output_to_pose.py#LL128C14-L128C14) to False. The PnP solver from opencv is faster and can save time in the debug stage. After you solved everything, you can change it back.

"not enough icp points" usually means the predicted pose is wrong (the predicted pose is somewhere in the background containing no depth measurement). I do not remember the red mask on the renderer. I haven't used ICP for a while.



Instead of copy the lib to /usr/lib, you can also add it into the LD_LIBRARY_PATH similar to here:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/Binary_Code_GT_Generator/Render_GT_Color_Mesh_to_GT_Img/build
