### ISSUE TITLE
Pretrained LM-O weights

### ISSUE THREAD

**Issue by LeroyChou** [suyz526/ZebraPose#27]
Hi,
   Thank you for your great work. I'm very interested in your proposed method and wanna reproduce the results on LM-O, but it seems that you didn't provide pretrained weight of each object. It would be very kind if you make the pretrained weights publicly available. 
Best regards
Leroy

**Comment by suyz526** [comment]
Hi Leroy,

thanks for your interested. 

We have provided model for each object. In the folder `paper`, we provided the model trained with real+pbr images. In the folder `bop`, the LM-O objects are trained only with pbr images (as the BOP challenge requires). For the symmetric objects that are symmetry-aware trained, their weights are saved in `bop_sat`. The `bop_sat` folder has less models, since the missing models can be taken from the `bop` folder.

Please also note that the LM-O dataset has less objects than LM dataset.


Best Regards,
Yongzhi
